Bookstore: Add & Remove Book Card, Use Dispatcher, Filter by Categories
romans-adi/bookstore pull request #3
Opened 2023-06-13 21:01 UTC by romans-adi

Pull Request Description:

## Add and Remove components, Dispatcher, Book Card
- Added 3 book objects to the initial state in all books array within `booksSlice.js`.
- Display books received from the Redux slice (`booksSlice.js`) in the `Home` component using a reusable `book-card` component.
- Modified the `generateRandomKey` function to generate new IDs based on the previous IDs, following the counters' sequence.
- Utilized the `dispatch` function to provide actions for the `handleAddBook`, `handleRemoveBook`, and `handleSelectCategory` functions.

## Selection by category (optional requirement)
- Implemented styles for the `book-category` button (label).
- Updated the prop type for the `RemoveBook` component to accept a string for the id property.

2023-06-13 21:27 UTC, Felix45 requested changes
Hi @romans-adi l, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Redux store is well set up correctly :white_check_mark: 
- [x] The structure of the files follows the duck's pattern :white_check_mark: 
- [x]  The repository has a professional readme file :white_check_mark: 
- [x]  Pull request has a descriptive summary and title :white_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 21:27 UTC, Felix45 commented on src/components/Home/RemoveBook.jsx
>  // eslint-disable-next-line import/no-extraneous-dependencies
- [ Required ] I think it would be better if you fix this `Eslint` error, disabling linter errors is not considered a good practice in software development especially if it's done in code. If you have to disable the `eslint` rule it would be better if you do it from the `.eslintrc.json` file as shown in the example below.

## Example code
```JavaScript
{
  "env": {
    "browser": true,
    "es6": true,
    "jest": true
  },
  "parser": "@babel/eslint-parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "extends": ["airbnb", "plugin:react/recommended", "plugin:react-hooks/recommended"],
  "plugins": ["react"],
  "rules": {
    "react/jsx-filename-extension": ["warn", { "extensions": [".js", ".jsx"] }],
    "react/react-in-jsx-scope": "off",
    "import/no-unresolved": "off",
    "import/no-extraneous-dependencies": "off",
    "no-shadow": "off",
    "no-console": "off",
    "import/no-extraneous-dependencies": "off"
  },
  "overrides": [
    {
      "files": ["src/**/*Slice.js"],
      "rules": { "no-param-reassign": ["error", { "props": false }] }
    }
  ],
  "ignorePatterns": [
    "dist/",
    "build/"
  ]
}
```

2023-06-13 21:27 UTC, Felix45 commented on src/components/Home/Home.jsx
> +// eslint-disable-next-line import/no-extraneous-dependencies
- [ Required ] I think it would be better if you fix this `Eslint` error, disabling linter errors is not considered a good practice in software development especially if it's done in code. If you have to disable the `eslint` rule it would be better if you do it from the `.eslintrc.json` file as shown in the example below.

## Example code
```JavaScript
{
  "env": {
    "browser": true,
    "es6": true,
    "jest": true
  },
  "parser": "@babel/eslint-parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "extends": ["airbnb", "plugin:react/recommended", "plugin:react-hooks/recommended"],
  "plugins": ["react"],
  "rules": {
    "react/jsx-filename-extension": ["warn", { "extensions": [".js", ".jsx"] }],
    "react/react-in-jsx-scope": "off",
    "import/no-unresolved": "off",
    "import/no-extraneous-dependencies": "off",
    "no-shadow": "off",
    "no-console": "off",
    "import/no-extraneous-dependencies": "off"
  },
  "overrides": [
    {
      "files": ["src/**/*Slice.js"],
      "rules": { "no-param-reassign": ["error", { "props": false }] }
    }
  ],
  "ignorePatterns": [
    "dist/",
    "build/"
  ]
}
```

2023-06-13 21:27 UTC, Felix45 commented on src/redux/books/booksSlice.js
>  import { createSlice } from '@reduxjs/toolkit';
- [ Required ] I think it would be better if you fix this `Eslint` error, disabling linter errors is not considered a good practice in software development especially if it's done in code. If you have to disable the `eslint` rule it would be better if you do it from the `.eslintrc.json` file as shown in the example below.

## Example code
```JavaScript
{
  "env": {
    "browser": true,
    "es6": true,
    "jest": true
  },
  "parser": "@babel/eslint-parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "extends": ["airbnb", "plugin:react/recommended", "plugin:react-hooks/recommended"],
  "plugins": ["react"],
  "rules": {
    "react/jsx-filename-extension": ["warn", { "extensions": [".js", ".jsx"] }],
    "react/react-in-jsx-scope": "off",
    "import/no-unresolved": "off",
    "import/no-extraneous-dependencies": "off",
    "no-shadow": "off",
    "no-console": "off",
    "import/no-extraneous-dependencies": "off"
  },
  "overrides": [
    {
      "files": ["src/**/*Slice.js"],
      "rules": { "no-param-reassign": ["error", { "props": false }] }
    }
  ],
  "ignorePatterns": [
    "dist/",
    "build/"
  ]
}
```

2023-06-13 21:27 UTC, Felix45 commented on src/components/Home/Home.jsx
> +  const books = useSelector(selectBooksByCategory);
- [ Required ] I think it would be better if the books in the redux store are accessed using the `useSelector` hook, you don't need to create a function for this. I would like to suggest that you use the code below as an example for accessing the books in the store.

```JavaScript
 const books = useSelector((state) => state.books.books)
```

2023-06-13 21:37 UTC, romans-adi commented on src/components/Home/Home.jsx
> +  const books = useSelector(selectBooksByCategory);
That's a good tip! Thank you.

2023-06-13 23:51 UTC, romans-adi commented on src/redux/books/booksSlice.js
>  import { createSlice } from '@reduxjs/toolkit';
I think it would be better if you check `package.json` first.

2023-06-14 00:23 UTC, Reem-lab approved these changes
# Hi @romans-adi,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights
- [ ] Great job on the funtionality for the use Redux in React component💯
- [ ] Followed Gitflow 🔥
- [ ] No Linters error ✅


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 11:58 UTC, romans-adi commented
Thank you very much for your review! Have a good day! :fireworks:

2023-06-14 11:58 UTC, closed without merging